# Site settings
title: Lucas Moraes - Desenvolvedor Front End
email: lucasdmwork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog desenvolvido para vocês
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "aboutlucas.github.io/blog/" # the base hostname & protocol for your site
github_username:  aboutlucas

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
